name: quiz_app
description: "A new Flutter project."

# The version and build number for your application.
version: 1.0.0+1

# Flutter SDK environment version
environment:
  sdk: ">=2.12.0 <3.0.0"  # Updated SDK version to match more recent Flutter versions

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2  # Updated to a newer version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Define assets here
  assets:
    - assets/images/  # Make sure to end with a trailing slash if it's a directory
